[package]
name = "pitr_util"
version = "1.2.0"
authors = ["urlordjames <32751441+urlordjames@users.noreply.github.com>"]
license = "MIT"
edition = "2018"

[dependencies]
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }

auto_ops = "0.3"
